commaai/laika

- laika/rinex_file.py
> obs_data_chunks never used

- laika/iono.py
> self.grid_TEC does not exist anymore

- laika/raw_gnss.py
- tests/test_dop.py
Hi!
I notice that you calculate VDOP from time dilution factor.
I fixed it and I add functions for calculate PDOP and TDOP.
I add also simple unit tests to check that returned values are valid.
Best regards and thanks for your work!
F
> Fix VDOP, add more DOP measurements

- laika/rinex_file.py
One may find a station they want but the only data rate provided is too fast (eg: I want 30s data but only 1s data is published).
Stations also change data rates over time making this annoying.
With this, one can supply a 'rate' to the RINEXFile, removing the extra data that wasn't needed. This saves processing time and memory.
As far as I can tell this didn't introduce any new linting or flake errors.
> allow decimating rinex files if their rates are too fast

- examples/Compute_station_pos.ipynb
- examples/Walkthrough.ipynb
`rg 'sattelite' --files-with-matches | xargs sed -i 's/sattelite/satellite/g'`
> Fix sattelite -> satellite

- README.md
- laika/ephemeris.py
- laika/helpers.py
- laika/lib/orientation.py
- tests/test_prns.py
Didn't touch the notebooks, but there are a few in there still.
> Laika: Fix Typos

- laika/astro_dog.py
This fixes regressions from #55.
- the `get_frequencies` method got de-dented so it was no longer a method (and hid the rest of the methods)
- GPS has as L5 band not L3
> Fix AstroDog

- laika/raw_gnss.py
My own fault. Incorrect indent leads to not adding gnss measurements
> Fix read_raw_ublox after refactoring

- laika/helpers.py
- laika/raw_gnss.py
Create UbloxGnssId enum
Fix final sat pos returning numpy array
Both used for laikad in openpilot.
Verified by running laikad.
Other small changes:
- Passed on signal variable in calc_vel_fix
- Some refactoring and type hints
> Add UbloxGnssId enum and fix sat_pos_final to be numpy array

- laika/raw_gnss.py
- tests/test_positioning.py
Test was previously enabled but actually isn't so slow if not calculating all measurements
> Enable position test for rinex observations

- laika/helpers.py
- tests/test_prns.py
Removing code is fun. Using a dictionary is much easier and more readable.
Still need to test other repos and usages since I removed all the warnings.
> Refactor prn to nmea and vice versa

- laika/ephemeris.py
- tests/test_ephemerides.py
Noticed a speedup from 16 to 14 sec
Verified by unit tests
> Speed up reading ephemeris data by using numpy array instead of loop

- laika/astro_dog.py
Forgot to refactor this function after refactoring the others.
> Refactor get_ionex function

- laika/astro_dog.py
- laika/raw_gnss.py
Change auto_update to use_internet and add argument to allow for less measurements to create a position fix
> Use_internet argument and pos fix minimal measurements

- laika/astro_dog.py
- laika/ephemeris.py
Plus Add_navs and Add_orbits now accept dictionaries
> Add Json helper functions for Ephemeris

- laika/ephemeris.py
- laika/raw_gnss.py
- tests/test_ephemerides.py
Adds file_source: first 3 letters of the file name to distinguish file types (e.g. igu or Sta (both ultra-rapid however one from nasa source and the latter from glonassIac source)
Adds file_epoch: first epoch present in the file to know the timestamp of the ephemeris file.
With the combination we can find out if a gnssmeasurement was created using for example the file 'Stark_1D_22061518.sp3' or 'igu22144_00.sp3.Z'
> GnssMeasurements: add ephemeris type and file info + scipy locally

- laika/ephemeris.py
this reverts the improvement from:
https://github.com/commaai/laika/commit/877d29dca64140e71d7a6d356b20b5eb56bc1e9a
but it makes qcom gps work, think we should re-add the improvement though
> make qcom-gps work

- laika/downloader.py
Hey, i added ftp-ssl support for cddis data according to issue #52.
> adding ftp-ssl for cddis data

- laika/ephemeris.py
this seems to be majorly wrong, currently testing it
> qcom glonass timing FIX

- laika/opt.py
- tests/test_positioning.py
- add std to gauss newton
- cleanUp opt file, move weights into gauss newton
> Laika std gauss newton

- laika/__init__.py
- laika/downloader.py
- laika/raw_gnss.py
- laika/rinex_file.py
Replace prints with logging module #125
> print -> logging

- .github/workflows/tests.yml
- setup.py
check that laika works after installing it (with a minimal test by importing it)
> Test the setup.py install process more rigorously

- .pre-commit-config.yaml
- examples/kalman/models/car_kf.py
- examples/kalman/models/gnss_kf.py
- laika/astro_dog.py
- laika/downloader.py
- laika/ephemeris.py
- laika/helpers.py
- laika/opt.py
- laika/raw_gnss.py
- laika/rinex_file.py
- pyproject.toml
1. update ruff hook
2. add pyupgrade pre-commit hook
3. run pyupgrade (`pre-commit run -a`)
4. `ruff --fix`
5. remove pyupgrade hook
> use pyupgrade to update typing syntax

- .github/workflows/tests.yml
- laika/downloader.py
- laika/ephemeris.py
- laika/gps_time.py
- setup.py
- tests/test_downloader.py
TODO: deal with version numbers > 0
NOTE: Since week 2238, no version numbers > 0 have been uploaded
> igs new product names
